---
efiBootLoader: "grub"
efiBootloaderId: "ClearwaterOS"
installEFIFallback: true
installHybridGRUB: true
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
kernelParams:
  - "quiet"
