---
services:
  - name: NetworkManager
    mandatory: true
  - name: bluetooth
    mandatory: false
  - name: cups
    mandatory: false
  - name: firewalld
    mandatory: false
  - name: sddm
    mandatory: true
  - name: systemd-resolved
    mandatory: false
  - name: systemd-timesyncd
    mandatory: false
